import React from 'react'
import { useEffect, useState } from 'react';


// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


// import { ThemeProvider, Frame , createTheme, Arwes, Button } from 'arwes';
// @ts-ignore: Unreachable code error

import { Arwes, ThemeProvider, Frame, Loading, Button, List, Link, Heading, Paragraph, createTheme } from 'arwes';

import Header from '@/components/Header';




const Stake = () => {
    const [hydrated, setHydrated] = useState(false);
    useEffect(() => {
        // Hydrate Arwes components on client-side
        setHydrated(true);
    }, []);
    const [audio3] = useState<HTMLAudioElement | undefined>(
        typeof Audio !== "undefined" ? new Audio("sounds/ask.mp3") : undefined
    );
    const start = () => {
        audio3?.play()
    }

    return (
        <>
            <ThemeProvider theme={createTheme()}>
                {hydrated ? (
                    <Arwes animate show background='background.jpg' pattern='glow.png'>
                        <Header activeClass="1" />

                        <div className="container">
                            <div className="row mx-0 mt-5 pt-5">
                                <div className="col-lg-1"></div>
                                <div className="col-lg-10">

                                    <Heading className="mt-4">
                                        🌌Nexus NFT Multi-Staking
                                    </Heading>
                                    <Paragraph>
                                        Stake NEXU, THE NEXUS NFTs, & Nexus to harvest the rewards generated by the NEXU Factory, NEXU Diffuser. This staking system distributes a variety of tokens and token pairs. Some tokens are NEXU, Nexus NLPs and more. Main examples of NLPs are NEXU pairs like NEXU/WBTC, NEXU/USDT. NLPs from future pairs with NEXU will be distributed here.
                                    </Paragraph>
                                    <Link>Learn More</Link>
                                    <Heading className="mt-4">
                                        Parameters📜
                                    </Heading>
                                    <List node='ul'>
                                        <li>Stake just NEXU with or without a timelock. The timelock multiplies your NEXU Power giving you a larger share of the pool.</li>
                                        <li>To add NEXU NFTs you must stake the minimum amount of NEXU one time and you must also stake the minimum NEXU amount per NFT.</li>
                                        <li>Consequences for breaking the spacetime barrier: Forfeit 50% of your locked NEXU. Half of this NEXU gets sent to the void. Half goes back to the Loyal Stakers.</li>
                                        <li>If you are not yet wise, it is recommended to experiment with the system using negligible amounts of tokens before going all In</li>
                                        <li>Your Pool Share percentage will change as other Nexus travellers move in and out of the pool.</li>

                                    </List>
                                    <div className="row mx-0 my-2" style={{ gap: "20px 0px" }}>
                                        <div className="col-lg-5">
                                            <Frame
                                                animate={true}
                                                level={1}
                                                corners={4}
                                                layer='primary'
                                                className="w-100"
                                            >
                                                <div className="p-3">
                                                    <div className="d-flex justify-content-center">
                                                        <img src="NEXUS.png" alt="" className="nexus__img" />
                                                    </div>
                                                    <div className="d-flex gap-3 align-items-center mt-2">
                                                        <Heading node="h3" className="mb-0">Nexus Diffuser</Heading>
                                                        <i className='fa-solid fa-info'></i>
                                                    </div>
                                                    <div className="d-flex align-items-center gap-2 mt-3">
                                                        <div>😀</div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>NLP Available:</Paragraph></div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>No</Paragraph></div>
                                                    </div>
                                                    <div className="d-flex align-items-center gap-2 mt-1">
                                                        <div>🔥</div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>Nexus Burned:</Paragraph></div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>210.919</Paragraph></div>
                                                    </div>
                                                    <div className="d-flex align-items-center gap-2 mt-1">
                                                        <div>🔥</div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>Nexus Burned:</Paragraph></div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>30.1159</Paragraph></div>
                                                    </div>
                                                    <div className="d-flex align-items-center gap-2 mt-1">
                                                        <div>🌭</div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>Nexus MultiStaking:</Paragraph></div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>60.2281</Paragraph></div>
                                                    </div>
                                                    <div className="d-flex align-items-center gap-2 mt-1">
                                                        <div>🏦</div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>Nexus Treasury:</Paragraph></div>
                                                        <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>0</Paragraph></div>
                                                    </div>
                                                    <div className="d-flex my-4 justify-content-center">
                                                        <Button>DIFFUSE</Button>
                                                    </div>
                                                </div>
                                            </Frame>
                                        </div>
                                        <div className="col-lg-7">

                                            <Frame animate={true}
                                                level={1}
                                                corners={4}
                                                layer='primary'
                                                className="w-100 h-100">
                                                <div className="p-3 pt-lg-5">
                                                    <div className="row mx-0">
                                                        <div className="col-lg-6">
                                                            <Heading node="h3">Global Stats🌎</Heading>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>Current Global Pool Size: 289712</Paragraph>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>Total NEXUS Locked: 29816</Paragraph>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>Total NEXUS NFTs Locked: 10</Paragraph>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>Total NEXUS Collatoral Locked: 700</Paragraph>
                                                            <Button className="mt-2">Distribute</Button>
                                                            <div className="d-flex gap-2 mt-2 align-items-center">
                                                                <Button>
                                                                    <img style={{ width: "40px" }} src="nexus22.png" alt="" />
                                                                </Button>
                                                                <div>
                                                                    <Paragraph className="mb-0" style={{ fontSize: "16px" }}>
                                                                        NEXUS LEFT: 0</Paragraph>
                                                                    <Paragraph className="mb-0" style={{ fontSize: "16px" }}>NEXT DIST: Now</Paragraph>

                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div className="col-lg-6">
                                                            <Heading node="h3">Distributed</Heading>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>NEXU: 4450870</Paragraph>
                                                            <Paragraph className="mb-0" style={{ fontSize: "16px" }}>NLP: 100</Paragraph>
                                                        </div>
                                                    </div>
                                                </div>

                                            </Frame>

                                        </div>
                                        <div className="col-lg-7">

                                            <Frame animate={true}
                                                level={1}
                                                corners={4}
                                                layer='primary'
                                                className="w-100 h-100">
                                                <div className="p-3 ">
                                                    <div className="d-flex justify-content-between">
                                                        <Heading>🌌Nexus Staking</Heading>
                                                        <Button><i className='fa-solid fa-plus'></i></Button>
                                                    </div>
                                                    <Frame animate={true}
                                                        level={1}
                                                        corners={4}
                                                        layer='primary'
                                                        className="w-100">
                                                        <div className="d-flex justify-content-between align-items-center px-4 py-3 pb-0">
                                                            <div>
                                                                <Heading className="mb-0">0.00</Heading>
                                                                <Paragraph className="mb-0" style={{ fontSize: "8px" }}>≈$0.00</Paragraph>
                                                            </div>
                                                            <div>
                                                                <Heading className="mb-0">NEXU</Heading>
                                                            </div>

                                                        </div>
                                                        <hr className='mb-0' />
                                                        <div className="d-flex justify-content-between align-items-center px-4 py-3">
                                                            <div>
                                                                <Paragraph className="mb-0" style={{ fontSize: "16px" }}>
                                                                    <i className='fa-solid fa-wallet me-2'></i>
                                                                    <span>Balance:</span>
                                                                </Paragraph>
                                                            </div>
                                                            <div>
                                                                <Paragraph className="mb-0" style={{ fontSize: "16px" }}>
                                                                    0 NEXU
                                                                </Paragraph>
                                                            </div>

                                                        </div>
                                                    </Frame>
                                                    <div className="mt-3">
                                                        <Heading node="h5">🌌Space-Time⏲ Lock🔒
                                                        </Heading>
                                                        <div className="d-flex justify-content-between">
                                                            <div><Paragraph className="mb-0">1x</Paragraph></div>
                                                            <div><Paragraph className="mb-0">1.5x</Paragraph></div>
                                                            <div><Paragraph className="mb-0">7x</Paragraph></div>
                                                            <div><Paragraph className="mb-0">15x</Paragraph></div>
                                                            <div><Paragraph className="mb-0">31x</Paragraph></div>
                                                        </div>
                                                        <input type="range" id="vol" name="vol" min="0" max="5" className='w-100' />
                                                        <div className="d-flex justify-content-between">
                                                            <div><Paragraph className="mb-0">0</Paragraph></div>
                                                            <div><Paragraph className="mb-0">1M</Paragraph></div>
                                                            <div><Paragraph className="mb-0">3M</Paragraph></div>
                                                            <div><Paragraph className="mb-0">6M</Paragraph></div>
                                                            <div><Paragraph className="mb-0">1Y</Paragraph></div>
                                                        </div>
                                                        <div className="text-center mt-5">
                                                            <Button className="w-100">Connect</Button>
                                                        </div>
                                                        <div className="text-center mt-5">
                                                            <Button className="w-100">Extend Lock</Button>
                                                        </div>
                                                    </div>
                                                </div>

                                            </Frame>


                                        </div>
                                        <div className="col-lg-5">
                                            <div className="d-flex flex-column justify-content-between h-100">
                                                <Frame animate={true}
                                                    level={1}
                                                    corners={4}
                                                    layer='primary'>
                                                    <div className="p-3">
                                                        <Heading node="h3">Stake Balance🥩</Heading>
                                                        <div className="d-flex gap-3 align-items-center mt-2">
                                                            <div>
                                                                <img src="nexusicon.png" style={{ width: "25px" }} alt="" />
                                                            </div>
                                                            <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>NEXUS</Paragraph></div>
                                                        </div>
                                                        <div className="d-flex gap-3 align-items-center mt-2">
                                                            <div>
                                                                <img src="alienicon.webp" style={{ width: "25px" }} alt="" />
                                                            </div>
                                                            <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>NEXUS NFT :0</Paragraph></div>
                                                        </div>
                                                        <div className="d-flex gap-3 align-items-center mt-2">
                                                            <div>
                                                                <img src="collaterol.png" style={{ width: "25px" }} alt="" />
                                                            </div>
                                                            <div><Paragraph className="mb-0" style={{ fontSize: "16px" }}>NEXUS Collatoral</Paragraph></div>
                                                        </div>
                                                        <Paragraph className="mb-0 mt-3" style={{ fontSize: "16px" }}>YOUR TOTAL POOL SHARE:
                                                            = 0.000000%</Paragraph>
                                                        <Paragraph className="mb-0 mt-3" style={{ fontSize: "16px" }}>TIME LOCK</Paragraph>
                                                    </div>
                                                </Frame>
                                                <Frame animate={true}
                                                    level={1}
                                                    corners={4}
                                                    layer='primary'>
                                                    <div className="p-3">
                                                        <Heading node="h3">
                                                            Rewards🌟

                                                        </Heading>
                                                        <div className="row mx-0 mb-3">
                                                            <div className="col-6"> <Paragraph>Claimed</Paragraph></div>
                                                            <div className="col-6" style={{ borderLeft: "1px solid #fff", height: "100px" }}>
                                                                <Paragraph>Pending</Paragraph> </div>
                                                        </div>
                                                        <Button className="w-100 text-center">Harness</Button>
                                                    </div>
                                                </Frame>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="mt-5">
                                        <Heading>
                                            Select Your Nexus NFTs

                                        </Heading>
                                        <Paragraph>
                                            Select The Nexus you would like to deploy. Some Nexus NFTs wield more power than others, choose wisely! Each Nexus NFT selected must be paired with NEXU. Tap to select or select max 40 at a time.
                                        </Paragraph>
                                        <div className="d-flex gap-3">
                                            <Button>Select Max</Button>
                                            <Button>UNSELECT All</Button>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-center flex-wrap mt-5">
                                        <div className='d-flex align-items-center gap-1'>
                                            <i style={{ fontSize: "12px" }} className='fa-solid fa-wallet'></i>
                                            <Paragraph className="mb-0" style={{ fontSize: "12px" }}>Balance: 0.0000</Paragraph>
                                        </div>
                                        <div><Paragraph className="mb-0" style={{ fontSize: "12px" }}>Min NEXU Amount/NFT:
                                            100 NEXU</Paragraph></div>
                                        <div><Paragraph className="mb-0" style={{ fontSize: "12px" }}>Min NEXU Lock Amount:
                                            1111 NEXU + 1%</Paragraph></div>
                                    </div>
                                    <div className="d-flex mt-3 justify-content-center">
                                        <div>
                                            <Paragraph className="mb-0" style={{ fontSize: "12px" }}>Total NEXU Required For NFT Multiplier:
                                                0 xORACLE</Paragraph>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-center text-center    my-4">
                                        <Button className="w-100">Connect</Button>
                                    </div>
                                </div>
                                <div className="col-lg-1"></div>
                            </div>
                        </div>
                    </Arwes>
                ) : (
                    <div>
                        <p>Loading... Please Wait</p>
                    </div>
                )}
            </ThemeProvider>
        </>
    )
}

export default Stake